"use client";

import { AppLayout } from "@/components/app-layout";
import { euro } from "@/lib/format";
import { useEffect, useState } from "react";

export default function PartnerSettlementSnapshotPage({ params }: { params: Promise<{ id: string }> }) {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); const [reason, setReason] = useState("");
  useEffect(() => { void params.then(({ id }) => fetch(`/api/partner-settlements/${id}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "加载结算快照失败"); setData(payload); }).catch((error) => setMessage(error.message))); }, [params]);
  async function reverse() { if (!data || !reason.trim() || !window.confirm("确认撤销该结算快照吗？撤销后可重新结算，原快照仍会保留。")) return; const response = await fetch(`/api/partner-settlements/${data.batch.id}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason }) }); const payload = await response.json(); if (!response.ok) { setMessage(payload.error || "撤销失败"); return; } setMessage("结算已撤销"); setData({ ...data, batch: { ...data.batch, status: "reversed", reversal_reason: reason } }); }
  if (message && !data) return <AppLayout title="结算快照"><section className="card panel"><p className="error-text">{message}</p></section></AppLayout>;
  if (!data) return <AppLayout title="结算快照"><section className="card panel"><p className="muted">加载中…</p></section></AppLayout>;
  return <AppLayout title="结算快照" description="历史快照按确认时的名称和比例保存。"><section className="card panel"><div className="panel-header"><div><h2 className="panel-title">{data.batch.period_start} 至 {data.batch.period_end}</h2><p className="muted">状态：{data.batch.status === "confirmed" ? "已确认" : "已撤销"}</p></div><a className="btn compact" href="/partner-settlements">返回历史</a></div><div className="compact-report-card"><div>收入 <strong>{euro(Number(data.batch.total_income))}</strong></div><div>支出 <strong>{euro(Number(data.batch.total_expense))}</strong></div><div>净利润 <strong className={Number(data.batch.net_profit) < 0 ? "danger-text" : "profit"}>{euro(Number(data.batch.net_profit))}</strong></div></div><h3 className="panel-title">合伙人快照</h3><div className="settlement-grid">{data.partners.map((partner: any) => <article className="settlement-card" key={partner.id}><strong>{partner.partner_display_name_snapshot}</strong><div className="profit-card-metrics"><span>代收 <b>{euro(Number(partner.actual_collected))}</b></span><span>垫付 <b>{euro(Number(partner.actual_paid))}</b></span><span>实际留存 <b>{euro(Number(partner.actual_retained))}</b></span><span>应得利润 <b>{euro(Number(partner.profit_entitlement))}</b></span><span>结算余额 <b>{euro(Number(partner.settlement_balance))}</b></span></div></article>)}</div><h3 className="panel-title">比例分段</h3>{data.segments.map((segment: any) => <div className="settlement-history-row" key={segment.id}><span>{segment.segment_start} 至 {segment.segment_end}</span><span>收入 {euro(Number(segment.total_income))}</span><span>支出 {euro(Number(segment.total_expense))}</span><span>利润 {euro(Number(segment.net_profit))}</span><span>{JSON.stringify(segment.shares_snapshot)}</span></div>)}<h3 className="panel-title">转账快照</h3>{data.transfers.length ? data.transfers.map((transfer: any) => <p key={transfer.id}>{transfer.from_name_snapshot} → {transfer.to_name_snapshot}：{euro(Number(transfer.amount))}</p>) : <p className="muted">无需转账</p>}{data.batch.status === "confirmed" ? <div className="field"><label>撤销原因</label><textarea value={reason} onChange={(event) => setReason(event.target.value)} /><button className="btn danger" type="button" disabled={!reason.trim()} onClick={() => void reverse()}>撤销结算</button></div> : null}{message ? <p className="success-text">{message}</p> : null}</section></AppLayout>;
}
